### Create a new user
POST http://127.0.0.1:3000/auth/signup
Content-Type: application/json

{
    "email": "ewerton@email.com",
    "password": "123456"
}

### list all users
GET http://127.0.0.1:3000/auth/users

### list a users
GET http://127.0.0.1:3000/auth/users/2
